Update dependencies and update to reflect new PHP Parser changes.
php-gettext/PHP-Scanner pull request #16
Opened 2024-03-08 04:01 UTC by BusterNeece

This PR changes the following:
 - Updates `composer.json` to depend on `nikic/php-parser` version 5.x instead of 4.x
 - Bump the minimum PHP version from 7.2 to 7.4 (php-parser itself only supports 7.4 and up)
 - Bump the versions of the testing dependencies
 - Update factory instantiation to reflect php-parser's new syntax
 - Slightly update how comments are parsed to handle changes in the parser

2024-03-09 12:01 UTC, oscarotero requested changes
Thanks!
I just left a couple of comments to fix a bug regarding numeric arguments.

2024-03-09 12:01 UTC, oscarotero commented on tests/PhpFunctionsScannerTest.php
> +        $this->assertSame(['arg1', 'arg2', null], $function->getArguments());
Looks like numeric arguments are not supported. Is it possible to fix that?

2024-03-09 12:01 UTC, oscarotero commented on tests/PhpFunctionsScannerTest.php
> +        $this->assertSame([null, null], $function->getArguments());
Other example of numeric arguments not being extracted.

2024-03-09 20:51 UTC, BusterNeece commented
@oscarotero Issues with numeric args should be fixed now. I initially couldn't tell what was causing that, but it turns out it was a simple problem with a simple fix.

2024-03-10 01:27 UTC, BusterNeece commented
@oscarotero Just pushed an update that should fix the GitHub Actions, setting them to run from 7.4 up, and downgrading PHPUnit to the latest stable version that supports that far back. You could certainly set the minimum PHP requirement higher, but I wanted to have as few BC breaks as possible in the PR.

2024-03-10 12:08 UTC, oscarotero approved these changes

2024-03-10 12:09 UTC, merged

2024-03-10 12:10 UTC, oscarotero commented
Great work!
Thank you!